name: 'version-bump'
description: 'bump the semver version'

inputs:
  version_tag:
    description: 'version tag to use'
    required: false
    default: "next_tag"
    type: string

outputs:
  version_tag:
    description: "version tag"
    value: ${{ steps.version.outputs.version_tag }}

  version_tag_numeric:
    description: "version tag with only numeric or ."
    value: ${{ steps.version.outputs.version_tag_numeric }}

runs:
  using: "composite"
  steps:
      # adjust the path so scripts in this repo can be run
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - id: version
      run: version-bump.sh
      shell: bash
      # handle when empty input is provided
      env:
        GHA_TAG: ${{ inputs.version_tag }}

