name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check some build related things
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git diff
          ls -la .

      - name: keep version as it has been manually provided
        id: version
        uses: ORCID/version-bump-action@main
        with:
          version_tag: v2.0.1

      - name: test if keeping vars are right
        run: |
          if [[ "$version_tag_numeric" == '2.0.1' ]];then
            echo "winning"
          else
            exit 1
          fi

        shell: bash
        env:
          version_tag_numeric: ${{ steps.version.outputs.version_tag_numeric }}
          version_tag: ${{ steps.version.outputs.version_tag }}

      - name: find next version by bumping tag
        id: version_bumped
        uses: ORCID-dev/version-bump-action@main
        with:
          version_tag: next_tag

      - name: test if bumping vars are right
        run: |
          if [[ "$version_tag_numeric" == '0.0.2' ]];then
            echo "winning"
          else
            exit 1
          fi

        shell: bash
        env:
          version_tag_numeric: ${{ steps.version_bumped.outputs.version_tag_numeric }}
          version_tag: ${{ steps.version_bumped.outputs.version_tag }}




